name: CI Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  contract-tests:
    runs-on: ubuntu-latest 
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"
      - name: "setup packages"
        run: "npm install"
      - name: "Run tests"
        run: "npm run test"

